// Practice Lab presets.
//
// Each preset is a chord progression laid out as a sequence of bars. Inside a
// bar, one or more chords share the bar's beats — the `beats` field is the
// number of quarter-note beats that chord occupies. The sum of `beats` within
// a bar must equal `beatsPerBar`.
//
// Future extension: tracks can carry an MP3 URL and optional per-chord
// `timestampSec` for tempo-free audio sync. For the prototype, the metronome
// is the clock and `tempo` (BPM) drives everything.

export type Chord = {
  roman: string;
  symbol: string;
  beats: number;
  /**
   * Single root note triggered on beat 1 (simple, non-walking).
   * Used when the preset has synthBacking: true and no bassNotes array.
   */
  bassNote?: string;
  /**
   * Walking bass: one note per beat of this chord.
   * Length must equal `beats`. Takes priority over bassNote.
   */
  bassNotes?: string[];
};

export type Bar = {
  chords: Chord[];
};

export type Preset = {
  id: string;
  name: string;
  key: string;
  tempo: number;
  beatsPerBar: number;
  bars: Bar[];
  /** MP3 backing track URL (relative to /public, e.g. "/audio/foo.mp3"). */
  audioUrl?: string;
  /**
   * When true, Tone.js synthesized drums + bass are generated in sync with
   * the Transport. Bass notes come from each chord's bassNote / bassNotes.
   * The metronome click is automatically muted (drums provide the pulse).
   */
  synthBacking?: boolean;
  /** Drum/rhythm style. Defaults to 'straight'. */
  backingStyle?: 'straight' | 'swing';
  /**
   * Seconds into the MP3 where the first beat of the progression lands.
   * The metronome count-in starts at `audioStartSec - countInDuration`
   * so that the audio and chord display line up at beat 1.
   * Defaults to 0.
   */
  audioStartSec?: number;
  /**
   * When true, a Key selector is shown and the bass notes are transposed
   * in real time from `baseKey` to the selected key.
   */
  supportsAllKeys?: boolean;
  /** The key the bassNotes are written in. Required when supportsAllKeys is true. */
  baseKey?: string;
};

export const PRESETS: Preset[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // Isn't She Lovely — Stevie Wonder (Songs in the Key of Life, 1976)
  // Fake-book / play-along version: Eb major, Rock Shuffle ♩=131
  //
  // Structure (14-bar head):
  //   A (1-8):   VIm7 → II7 → V7sus → Imaj7  ×2
  //   B (9-14):  IVmaj7 → III7(♭9) → VIm7 → II7 → V7sus → I
  //
  // II7  = F7  (V/V — secondary dominant pulling to Bb7sus)
  // III7 = G7♭9 (V/vi — secondary dominant pulling back to Cm7)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'isnt-she-lovely-eb',
    name: "Isn't She Lovely (Key E♭)",
    key: 'E♭',
    tempo: 131,
    beatsPerBar: 4,
    audioUrl: '/audio/isnt-she-lovely.mp3',
    // The audio file has ~0.3s of silence + 2 bars (8 beats) of count-in
    // at 131 BPM before the chord progression starts.
    // audioStartSec = 0.319 + 8 × (60/131) ≈ 3.98s
    audioStartSec: 3.98,
    bars: [
      // A section (8 bars) ─────────────────────────────────────
      { chords: [{ roman: 'VIm7',     symbol: 'Cm7',    beats: 4 }] },
      { chords: [{ roman: 'II7',      symbol: 'F7',     beats: 4 }] },
      { chords: [{ roman: 'V7sus',    symbol: 'B♭7sus', beats: 4 }] },
      { chords: [{ roman: 'Imaj7',    symbol: 'E♭maj7', beats: 4 }] },
      { chords: [{ roman: 'VIm7',     symbol: 'Cm7',    beats: 4 }] },
      { chords: [{ roman: 'II7',      symbol: 'F7',     beats: 4 }] },
      { chords: [{ roman: 'V7sus',    symbol: 'B♭7sus', beats: 4 }] },
      { chords: [{ roman: 'Imaj7',    symbol: 'E♭maj7', beats: 4 }] },
      // B section / Bridge (6 bars) ────────────────────────────
      { chords: [{ roman: 'IVmaj7',   symbol: 'A♭maj7', beats: 4 }] },
      { chords: [{ roman: 'III7(♭9)', symbol: 'G7(♭9)', beats: 4 }] },
      { chords: [{ roman: 'VIm7',     symbol: 'Cm7',    beats: 4 }] },
      { chords: [{ roman: 'II7',      symbol: 'F7',     beats: 4 }] },
      { chords: [{ roman: 'V7sus',    symbol: 'B♭7sus', beats: 4 }] },
      { chords: [{ roman: 'I',        symbol: 'E♭',     beats: 4 }] },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  // ii-V-I in C — Synth drums + bass test preset
  // 4-bar loop: Dm7 → G7 → Cmaj7 (×2)
  // Drums and bass are generated by Tone.js, locked to the same Transport
  // as the metronome, so tempo changes apply instantly with zero drift.
  // ─────────────────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────
  // ii-V-I in C — Jazz Swing (Tone.js synth drums + walking bass)
  //
  // Drums: ride cymbal (jazz swing pattern), foot hihat on 2&4, light kick on 1
  // Bass: walking bass line — one note per beat, chord tones + approach notes
  //
  //   Dm7:   D2 - F2 - A2 - C3   (1-b3-5-b7 arpeggiated up)
  //   G7:    B2 - G2 - D3 - F3   (start from 3rd for smooth C3→B2 step)
  //   Cmaj7: E3 - D3 - C3 - A2   (descend from 3rd)
  //   Cmaj7: G2 - E2 - C2 - Eb2  (chromatic Eb2→D2 approach back to top)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ii-v-i-synth-c',
    name: 'ii-V-I in C — Jazz Swing',
    key: 'C',
    tempo: 120,
    beatsPerBar: 4,
    synthBacking: true,
    backingStyle: 'swing',
    supportsAllKeys: true,
    baseKey: 'C',
    bars: [
      { chords: [{ roman: 'IIm7',  symbol: 'Dm7',   beats: 4, bassNotes: ['D2', 'F2', 'A2', 'C3'] }] },
      { chords: [{ roman: 'V7',    symbol: 'G7',    beats: 4, bassNotes: ['B2', 'G2', 'D3', 'F3'] }] },
      { chords: [{ roman: 'Imaj7', symbol: 'Cmaj7', beats: 4, bassNotes: ['E3', 'D3', 'C3', 'A2'] }] },
      { chords: [{ roman: 'Imaj7', symbol: 'Cmaj7', beats: 4, bassNotes: ['G2', 'E2', 'C2', 'Eb2'] }] },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  // Mellow Soulful Groove — Key F, ♩=74 (148 double-time feel)
  //
  // YouTube jam track ("Mellow Soulful Groove Guitar Backing Track Jam in F").
  // No count-in in the audio — music starts at t≈0.52s (first note onset).
  // audioStartSec = 0.52.
  //
  // Progression (25 bars, Key F major):
  //   A (×3, 12 bars): | Dm7 | Bb | F | C |
  //   B (2 bars):      | Gm  | Bb |
  //   C (6 bars):      | Gm  | Bb | Dm | C | F | C |
  //   D (5 bars):      | Gm  | Bb | Dm | C | Bb |
  //
  // Roman numerals relative to F major:
  //   F=I  Gm=IIm  Bb=IV  C=V  Dm=VIm
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'groove-f-74bpm',
    name: 'Groove in F — 74 BPM (音源)',
    key: 'F',
    tempo: 74,
    beatsPerBar: 4,
    audioUrl: '/audio/groove-f-74bpm.mp3',
    audioStartSec: 0.52,
    bars: [
      // ── A section (×3 = 12 bars): Dm7 | Bb | F | C ────────────────────
      { chords: [{ roman: 'VIm7', symbol: 'Dm7', beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
      { chords: [{ roman: 'I',    symbol: 'F',   beats: 4 }] },
      { chords: [{ roman: 'V',    symbol: 'C',   beats: 4 }] },
      { chords: [{ roman: 'VIm7', symbol: 'Dm7', beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
      { chords: [{ roman: 'I',    symbol: 'F',   beats: 4 }] },
      { chords: [{ roman: 'V',    symbol: 'C',   beats: 4 }] },
      { chords: [{ roman: 'VIm7', symbol: 'Dm7', beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
      { chords: [{ roman: 'I',    symbol: 'F',   beats: 4 }] },
      { chords: [{ roman: 'V',    symbol: 'C',   beats: 4 }] },
      // ── B section (2 bars): Gm | Bb ───────────────────────────────────
      { chords: [{ roman: 'IIm',  symbol: 'Gm',  beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
      // ── C section (6 bars): Gm | Bb | Dm | C | F | C ─────────────────
      { chords: [{ roman: 'IIm',  symbol: 'Gm',  beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
      { chords: [{ roman: 'VIm',  symbol: 'Dm',  beats: 4 }] },
      { chords: [{ roman: 'V',    symbol: 'C',   beats: 4 }] },
      { chords: [{ roman: 'I',    symbol: 'F',   beats: 4 }] },
      { chords: [{ roman: 'V',    symbol: 'C',   beats: 4 }] },
      // ── D section (5 bars): Gm | Bb | Dm | C | Bb ─────────────────────
      { chords: [{ roman: 'IIm',  symbol: 'Gm',  beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
      { chords: [{ roman: 'VIm',  symbol: 'Dm',  beats: 4 }] },
      { chords: [{ roman: 'V',    symbol: 'C',   beats: 4 }] },
      { chords: [{ roman: 'IV',   symbol: 'Bb',  beats: 4 }] },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  // ii-V-I in C — MP3 backing track, ♩=65
  //
  // Full-band audio ("全楽器対応"). 1-bar count-in at 65 BPM before loop.
  //
  //   audioStartSec = count-in click onset (0.132s) + 4 beats × (60/65)
  //                 = 0.132 + 3.692 ≈ 3.82s
  //
  // Progression (2-bar loop):
  //   Bar 1: | Dm7 (2) · G7 (2) |
  //   Bar 2: | Cmaj7 (4)        |
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: '251-c-65bpm',
    name: 'ii-V-I in C — 65 BPM (音源)',
    key: 'C',
    tempo: 65,
    beatsPerBar: 4,
    audioUrl: '/audio/251-c-65bpm.mp3',
    audioStartSec: 3.82,
    bars: [
      {
        chords: [
          { roman: 'IIm7',  symbol: 'Dm7',   beats: 2 },
          { roman: 'V7',    symbol: 'G7',     beats: 2 },
        ],
      },
      { chords: [{ roman: 'Imaj7', symbol: 'Cmaj7', beats: 4 }] },
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ii-v-i-practice-c',
    name: 'ii-V-I Practice (Key C)',
    key: 'C',
    tempo: 120,
    beatsPerBar: 4,
    bars: [
      { chords: [{ roman: 'IIm7', symbol: 'Dm7', beats: 4 }] },
      { chords: [{ roman: 'V7', symbol: 'G7', beats: 4 }] },
      { chords: [{ roman: 'Imaj7', symbol: 'Cmaj7', beats: 4 }] },
      { chords: [{ roman: 'Imaj7', symbol: 'Cmaj7', beats: 4 }] },
      { chords: [{ roman: 'IIm7', symbol: 'Dm7', beats: 4 }] },
      { chords: [{ roman: 'V7', symbol: 'G7', beats: 4 }] },
      {
        chords: [
          { roman: 'Imaj7', symbol: 'Cmaj7', beats: 2 },
          { roman: 'VI7', symbol: 'A7', beats: 2 },
        ],
      },
      {
        chords: [
          { roman: 'IIm7', symbol: 'Dm7', beats: 2 },
          { roman: 'V7', symbol: 'G7', beats: 2 },
        ],
      },
    ],
  },
];

export const DEFAULT_PRESET_ID = PRESETS[0].id;

export function getPreset(id: string): Preset {
  return PRESETS.find((p) => p.id === id) ?? PRESETS[0];
}
